### ISSUE TITLE
scalismo.support.nativelibs.NativeLibraryException

### ISSUE THREAD

**Issue by yifanh1** [unibas-gravis/basel-face-model-viewer#13]
Thank you for this visualization tool!! 
I did the following:
    installed Java (Version 8.0 or higher recommended) I used java version "14.0.2" 2020-07-14.
    installed sbt (only for compiling from sources) sbt script version: 1.3.13
    download model-viewer.jar 
    run
```
java -Xmx2g -jar model-viewer.jar
```
And got the error:
```
scalismo.support.nativelibs.NativeLibraryException: Unable to load native library file /home/myname/.scalismo/native-libs-4.0/libnativewindow_awt.so
... (more)
```
OS: Ubuntu 18.04.5 LTS

I am quite new to Scala and Java. And there is no exact match at Stackoverflow.
How to solve this? Do I need to include Basel Model in the folder? 
Please tell me if any further information is needed.
Yifan

**Comment by BernhardEgger** [comment]
Hi Yifan,

there are two things that might go wrong here:
- I never tested it with java 14 - you might consider testing an older version?
- the awt-related issue could be caused my JOGL not installed

can you try those?

Bernhard

**Comment by KouMeanSun** [comment]
when I run shell "running faces.apps.ModelViewer -mem 2000"
It called  "scalismo.support.nativelibs.NativeLibraryException: Unable to load native library file C:\Users\gaomingyang\.scalismo\native-libs-4.0\nativewindow_awt.dll",

**Comment by BernhardEgger** [comment]
Can you try to install an older java version? e.g. java 8?

**Comment by ShreyaKapoor18** [comment]
I am running into the same issue 

Error: Unable to access jarfile app/generator.jar
chmod: cannot access 'home/hpc/b112dc/b112dc10/.scalismo/native-libs-4.0/libnativewindow_awt.so': No such file or directory
Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/home/hpc/b112dc/b112dc10/tmp
scalismo.support.nativelibs.NativeLibraryException: Unable to load native library file /home/hpc/b112dc/b112dc10/.scalismo/native-libs-4.0/libnewt.so
	at scalismo.support.nativelibs.impl.NativeLibraryBundle.loadLibraries(NativeLibraryBundle.java:239)
	at scalismo.support.nativelibs.impl.NativeLibraryBundle.initialize(NativeLibraryBundle.java:191)
	at scalismo.support.nativelibs.NativeLibraryBundlesImplementation.initialize(NativeLibraryBundlesImplementation.java:135)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at scalismo.support.nativelibs.NativeLibraryBundles.delegateInitializeCall(NativeLibraryBundles.java:169)
	at scalismo.support.nativelibs.NativeLibraryBundles.initialize(NativeLibraryBundles.java:59)
	at scalismo.package$.initialize(package.scala:39)
	at fitting.experiments.RecognitionMultiPiePose$.delayedEndpoint$fitting$experiments$RecognitionMultiPiePose$1(RecognitionMultiPIE.scala:33)
	at fitting.experiments.RecognitionMultiPiePose$delayedInit$body.apply(RecognitionMultiPIE.scala:32)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at fitting.experiments.RecognitionMultiPiePose$.main(RecognitionMultiPIE.scala:32)

**Comment by BernhardEgger** [comment]
Die you have a chance to try above solutions?
If not please indicate java version and OS at least
